# Generated by Django 3.2.3 on 2021-05-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
